In [11]:
import numpy as np

# Define the matrix
A = np.array([[1,2,3],[4,5,6],[7,8,9]])

# Perform SVD
U, S, VT = np.linalg.svd(A)

# Print the results
print("U matrix: \n", U)
print("Singular values: \n", S)
print("VT matrix: \n", VT)


U matrix: 
 [[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]
Singular values: 
 [1.68481034e+01 1.06836951e+00 4.41842475e-16]
VT matrix: 
 [[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [-0.40824829  0.81649658 -0.40824829]]
